version: 2
updates:
- package-ecosystem: npm
  directory: "/api"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/mongoose"
    versions:
    - "< 5.3.2, >= 5.3.1.a"
  - dependency-name: "@types/mongoose"
    versions:
    - 5.10.3
    - 5.10.4
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@types/chai"
    versions:
    - 4.2.14
    - 4.2.15
  - dependency-name: "@types/passport-jwt"
    versions:
    - 3.0.3
    - 3.0.4
  - dependency-name: markdown-it
    versions:
    - 12.0.4
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: jquery
    versions:
    - 3.5.1
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: gulp-mocha
    versions:
    - 7.0.2
